imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    session:
        domain: %session_domain%
        default_locale: %locale%
        auto_start:     true
        lifetime:       72000
        storage_id:     session.storage.pdo
 
parameters:
    pdo.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time  

services:    
    pdo:
        class: PDO
        arguments:
            - "%database_type%:dbname=%database_name%;host=%database_host%"
            - %database_user%
            - %database_password%
    session.storage.pdo:
            class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
            arguments: [@pdo, %session.storage.options%, %pdo.db_options%]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
 
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        hostname: %hostname%
        google_analytics: %google_analytics%
        directory: %directory%
        japan_map_url: %japan_map_url%
        api_url: %api_url%
        geoserver_url: %geoserver_url%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                mapping_types:
                    geometry: string
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  utf8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: Zeega\DataBundle\Entity\User
    from_email:
        address: noreply@zeega.org
        sender_name: Zeega
    resetting:
        email:
            template: ZeegaUserBundle:Email:resetting.email.twig
    registration:
        form:
            type: zeega_user_registration
                
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
