security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_memory_provider:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            form_login:
                provider: fos_userbundle
                default_target_path: /en/success
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /en/home
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ja/home, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ja/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
