security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            form_login:
                provider: fos_userbundle
                default_target_path: /en/success
                login_path: /login 
            logout:
                path:   /logout
                target: /en/home
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ja/home, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ja/search, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/about role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/about role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ja/about role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
