_security_login:
    pattern:   /{_locale}/login
    defaults: { _controller:  ZeegaUserBundle:Security:login, _locale: ja }
    requirements:
        _locale: en|ja

_security_check:
    pattern:  /{_locale}/login_check
    requirements:
        _locale: en|ja

_security_logout:
    pattern:  /logout
