default:
    pattern:   /
    defaults:  { _controller: JDACoreBundle:Home:redirect, _locale: ja }
search:
    pattern:   /{_locale}/search
    defaults:  { _controller: JDACoreBundle:Search:index, _locale: ja }
    requirements:
        _locale: en|ja
advsearch:
    pattern:   /{_locale}/advsearch
    defaults:  { _controller: JDACoreBundle:AdvSearch:index, _locale: ja }
    requirements:
        _locale: en|ja
home:
    pattern:   /{_locale}/home
    defaults:  { _controller: JDACoreBundle:Home:index, _locale: ja }
    requirements:
        _locale: en|ja
about:
    pattern:   /{_locale}/about
    defaults:  { _controller: JDACoreBundle:About:index, _locale: ja }
    requirements:
        _locale: en|ja

collections:
    pattern:   /{_locale}/collections
    defaults:  { _controller: JDACoreBundle:Collections:index, _locale: ja }
    requirements:
        _locale: en|ja
item:
    pattern:   /{_locale}/item/{item_id}
    defaults:  { _controller: JDACoreBundle:Item:index, _locale: ja }
    requirements:
        _locale: en|ja
seedSubmit:
    pattern:   /{_locale}/seedSubmission/
    defaults:  { _controller: JDACoreBundle:SeedSubmitController:index, _locale: ja }
    requirements:
        _locale: en|ja