parameters:
#    zeega_jda.example.class: JDA\CoreBundle\Example

services:
#    zeega_jda.example:
#        class: %zeega_jda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
